package similarities;

public enum SimEnum {
    PEARSON_CORRELATION,
    EUCLIDEAN_SIMILARITY,
    EUCLIDEAN_DISTANCE,
    MANHATTAN_SIMILARITY,
    MANHATTAN_DISTANCE,
    CHEBYSHEV_SIMILARITY,
    CHEBYSHEV_DISTANCE,
    JACCARD_SIMILARITY,
    HAMMING_SIMILARITY,
}


